name: Convert Surge to Clash

on:
  push:
    branches: [main]
    paths: ['*.list']
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert rules
        run: bash Scripts/convert.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'Clash/'
          message: "chore: update clash rules"
          push: "origin HEAD:main"
